### ISSUE TITLE
installer not working

### ISSUE THREAD

**Issue by ghost** [konstantintuev/Aurora-Services#1]
realme 5i Devices
realme Ui Android 10

aurora Store version:
4.0.2

aurora Service Version:
2.0.0

i installed both of them in Work Profile

**Comment by konstantintuev** [comment]
I am using this app as the only Play Store on my daily device as it's a Huawei.
The moment I noticed that it wasn't working with the new Aurora Store, I investigated and made a new version compatible with the new Aurora Store but sadly the new Store is very buggy and it tries to install every app many times one after another.

So I recommend using Aurora Store v3 until v4 is in better shape (no bugs + auto background updates).
Currently Aurora Store v3 is broken for Huawei devices and anonymous login is not working but I have a fork of it in a better shape and will release it for people to use.

**Comment by ghost** [comment]
i waiting until you release v3 forked version
until then and until bug not resolve please do not close my issues

**Comment by ghost** [comment]
@konstantintuev  hi how it's going? when you will release that aurora store?

**Comment by konstantintuev** [comment]
I have submitted a merge request to the official AuroraStore fixing many things.
It's merged and a new update should be released soon, you can track the progress here: [GitLab link](https://gitlab.com/AuroraOSS/AuroraStore/-/merge_requests/130)

Also I have updated my custom AuroraServices, here is the newest build: [GitLab Releases Link](https://gitlab.com/konstantintuev/AuroraServices/-/releases/3.0.0)

The newest version of AuroraStore with my changes from above is required for everything to work as smooth as possible.

**Comment by ghost** [comment]
@konstantintuev  merge? i think you gonna release separate forked v3 version of aurora store....


> Currently Aurora Store v3 is broken for Huawei devices and anonymous login is not working but I have a fork of it in a better shape and will release it for people to use.

**Comment by konstantintuev** [comment]
Super happy to report that the official version (AuroraStore v4) works with Huawei even better thanks to spoofing.  
Also thanks to my changes background downloads are a lot more reliable because of a foreground (notification) service I've implemented.  
I have been using the newest AuroraStore and AuroraService for about a week on Huawei P40 Pro and it works perfectly!

**Comment by ghost** [comment]
> Super happy to report that the official version (AuroraStore v4) works with Huawei even better thanks to spoofing.
> Also thanks to my changes background downloads are a lot more reliable because of a foreground (notification) service I've implemented.
> I have been using the newest AuroraStore and AuroraService for about a week on Huawei P40 Pro and it works perfectly!

so you cancell to release aurora store forked v3? gimme that apk bro pls? 🥺 @konstantintuev

**Comment by konstantintuev** [comment]
Some more changes might be needed before a full public release but here is the Telegram channel with all of the newest AuroraStore builds based on any new change - [Link](https://t.me/AuroraGitlabCI).  
I am attaching the newest build from the Telegram channel here (unzip before install as apk is not allowed in GitHub):
[AuroraStore_CI_29062021-190045.apk.zip](https://github.com/konstantintuev/Aurora-Services/files/6738982/AuroraStore_CI_29062021-190045.apk.zip)

**Comment by ghost** [comment]
@konstantintuev  hi can you make fork of stripped version of aurora store?

I can't upload the apk is not allowed by GitHub do you have telegram that i can contact to? I share the apk there

Note:
Stripped version remove anonymous login temporary remain google login option but I can't login using stripped Version of aurora store

Need Fix:
Login to Google
Aurora Service ADB Over TCP Compatibility


Also don't do a pull request of this version whyorean won't approve that since this version discontinued i need this version to use dual account together 🙏

**Comment by konstantintuev** [comment]
Such version shouldn't be needed as you can use the official AuroraStore with own  Google account.
Also the newest version of my adb AuroraServices support the newest official AuroraStore.

**Comment by ghost** [comment]
> Such version shouldn't be needed as you can use the official AuroraStore with own Google account.
> Also the newest version of my adb AuroraServices support the newest official AuroraStore.

Nah i want to have 2 of them together

**Comment by konstantintuev** [comment]
AuroraStore 3 doesn't work at all anymore, still please use the official AuroraStore 4 and everything should be alright.

**Comment by ghost** [comment]
> AuroraStore 3 doesn't work at all anymore, still please use the official AuroraStore 4 and everything should be alright.

Even with forked version from you or someone else? :(((((((

**Comment by konstantintuev** [comment]
Yep

**Comment by ghost** [comment]
> Yep

OH H*LL NOOOOOOOOOOOOOO AAAAAAAAAAAAAAAAAAAAAAAAAAAA 😟

**Comment by ghost** [comment]
> Some more changes might be needed before a full public release but here is the Telegram channel with all of the newest AuroraStore builds based on any new change - [Link](https://t.me/AuroraGitlabCI). I am attaching the newest build from the Telegram channel here (unzip before install as apk is not allowed in GitHub): [AuroraStore_CI_29062021-190045.apk.zip](https://github.com/konstantintuev/Aurora-Services/files/6738982/AuroraStore_CI_29062021-190045.apk.zip)

Hi @konstantintuev i confused 
This channel release official version of aurora store by whyoeran or your fork?
